name: Build and deploy a container to an Azure Web App

# env:
#   AZURE_WEBAPP_NAME: demosandbox # set this to the name of your Azure Web App

on:
  push:
    branches: 
       - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#       - name: Log in to GitHub container registry
#         uses: docker/login-action@v1.10.0
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ github.token }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: vekawspocregistry.azurecr.io # default: index.docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Lowercase the repo name and username
      #   run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

#       - name: Build and push container image to registry
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
#           file: ./Dockerfile

      - name: Build the frontend image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vekawspocregistry.azurecr.io/poc-automation:latest
          file: Dockerfile


  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: vekawspocregistry.azurecr.io # default: index.docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
             docker ps -a
#          script: |
#            docker pull vekawspocregistry.azurecr.io/poc-automation:latest
#            docker build -t vekawspocregistry.azurecr.io/poc-automation:latest .
#            docker run -d vekawspocregistry.azurecr.io/poc-automation:latest
           
